// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// SECURITY NOTE: These values are PUBLIC and safe to expose in the client bundle.
// - SUPABASE_URL: Public project URL
// - SUPABASE_PUBLISHABLE_KEY: Public anon key (protected by Row Level Security)
// 
// Private secrets (service role key, Stripe keys, etc.) are stored in:
// - Supabase Edge Function secrets (accessed via Deno.env.get())
// - NEVER in frontend code or committed to git
const SUPABASE_URL = "https://viwxxjnehceedyctevau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpd3h4am5laGNlZWR5Y3RldmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDE3NzcsImV4cCI6MjA3MDc3Nzc3N30.bQqfq-ktOHrIs6cyCYx7t8PRmrn0oaO6qPUY2mGZOrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SSR-safe check for browser environment
const isBrowser = typeof window !== "undefined";

// SSR-safe storage getter
const getStorage = () => {
  if (typeof window === "undefined") return undefined;
  return window.localStorage;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
    detectSessionInUrl: isBrowser,
  }
});