// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viwxxjnehceedyctevau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpd3h4am5laGNlZWR5Y3RldmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDE3NzcsImV4cCI6MjA3MDc3Nzc3N30.bQqfq-ktOHrIs6cyCYx7t8PRmrn0oaO6qPUY2mGZOrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});